#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

LRED='\033[1;31m'
NC='\033[0m'

if ! head -1 "$1" | grep -qE "^(init|feat|fix|docs|refactor)(\(.+?\))?: .{1,}$"; then
  printf "\n${LRED}Aborting commit. Your commit message is invalid.${NC}\n" >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    printf "\n${LRED}Aborting commit. Your commit message is too long.${NC}\n" >&2
    exit 1
fi
